name: run-xpsec-test
on: [push]
jobs:
  test:
    env:
      SAXON_HOME: /opt/saxon
      SAXON_VERSION: 10.3
      XSPEC_HOME: /opt/xspec
      XPSEC_VERSION: v2.0.7
      SAXON_FILENAME: saxonhe.jar

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - run: mvn package
    - run: cd /opt/
    - run: git clone https://github.com/xspec/xspec.git && cd $XSPEC_HOME && git checkout $XSPEC_VERSION
    - run: mkdir $SAXON_HOME && cd $SAXON_HOME
    - run: curl -o $SAXON_FILENAME https://repo1.maven.org/maven2/net/sf/saxon/Saxon-HE/${SAXON_VERSION}/Saxon-HE-${SAXON_VERSION}.jar
