name: run-xpsec-test
on: [push]
jobs:
  test:
    env:
      SAXON_HOME: /opt/saxon
      SAXON_VERSION: 10.3
      XSPEC_HOME: /opt/xspec
      XPSEC_VERSION: v2.0.7
      SAXON_FILENAME: saxonhe.jar

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - run: mvn package
    - run: cd /opt && git clone https://github.com/xspec/xspec.git && cd $XSPEC_HOME && git checkout $XSPEC_VERSION
    - run: mkdir -p $SAXON_HOME/lib && cd $SAXON_HOME && curl -o $SAXON_FILENAME https://repo1.maven.org/maven2/net/sf/saxon/Saxon-HE/${SAXON_VERSION}/Saxon-HE-${SAXON_VERSION}.jar
    - run: cp file/target/*uber.jar $SAXON_HOME/lib/
    - run: ls $SAXON_HOME $XSPEC_HOME
    - run: cd $XSPEC_HOME && ant -lib $SAXON_HOME -lib $SAXON_HOME/lib -Dxspec.xml=$GITHUB_WORKSPACE/xspec/file.xspec -Dsaxon.custom.options="-config:$GITHUB_WORKSPACE/xspec/config.xml"
      if: success() || failure()
    - run: cd $GITHUB_WORKSPACE && mkdir report && cp $GITHUB_WORKSPACE/xspec/xspec/file-result.html $GITHUB_WORKSPACE/report
      if: success() || failure()
    
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@4.0.0
      with:
        branch: gh-pages # The branch the action should deploy to.
        folder: report # The folder the action should deploy.
      if: success() || failure()
    
    - run: echo "see failed test result in https://oyvindlgjesdal.github.io/saxon-extensions/file-result.html"
